version: "3.9"

services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend/users.txt:/app/users.txt

  frontend:
    build: ./frontend
    container_name: flask-frontend
    ports:
      - "8000:8000"
    environment:
      BACKEND_URL: http://backend:9000
    depends_on:
      - backend
