apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-frontend
  template:
    metadata:
      labels:
        app: devops-frontend
    spec:
      containers:
      - name: devops-frontend
        image: docker.io/sandeep120990/devops-frontend
        ports:
        - containerPort: 8000
        env:
        - name: BACKEND_URL
          value: http://devops-backend:9000


---
apiVersion: v1
kind: Service
metadata:
  name: devops-frontend
spec:
  selector:
    app: devops-frontend
  ports:
  - port: 80
    targetPort: 8000
